name: worldgourd
version: "${version}"
main: org.enginehub.worldgourd.bukkit.WorldGourdPlugin
api-version: 1.20
authors: [ EngineHub ]
description: WorldGourd, a premier Minecraft pumpkin protection plugin
softdepend: [ WorldEdit ]
folia-supported: true
